before_script:
  - npm install -g grunt-cli
language: node_js
node_js:
  - "0.10"
  - "0.12"
sudo: false
before_install:
  # Remove all non-test dependencies
  - npm rm --save-dev grunt-contrib-watch
  # Skip installing optional dependencies
  - npm config set optional false
